# Generated by Django 3.2.19 on 2023-06-24 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0003_auto_20230623_2116'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuario',
            new_name='Usuario2',
        ),
    ]
