# Generated by Django 3.2.19 on 2023-07-05 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0004_rename_usuario_usuario2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TiposDeObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='producto',
            name='creacion_fecha',
        ),
        migrations.AddField(
            model_name='producto',
            name='año',
            field=models.IntegerField(default=2023),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(default='escribe una descripcion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='productos/imagenes')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galeria.producto')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tipos_de_obra',
            field=models.ManyToManyField(to='galeria.TiposDeObra'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='galeria.autor'),
        ),
    ]
