# Generated by Django 3.2.20 on 2023-07-06 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0005_auto_20230704_2100'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usuario2',
            table='galeria_usuario2',
        ),
    ]
