# Generated by Django 3.2.20 on 2023-07-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0006_alter_usuario2_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
