# Generated by Django 3.2.20 on 2023-07-07 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0007_producto_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='mensaje_rechazo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='rechazado',
            field=models.BooleanField(default=False),
        ),
    ]
